### ISSUE TITLE
As an admin, expecting better naming convention for Job and Resume objects aligned with candidates.

### ISSUE THREAD

**Issue by nehahimane** [harshchauhdary/Solvers-Soen6011summer2023#26]

**Comment by harshchauhdary** [comment]
The fields in Job and Resume objects in the admin portal are:
Job: Position, Description, ApplicationDeadline, Status, Employer
Resume: Summary, Education, Experience, Skills, File

Can you please elaborate?

**Comment by harshchauhdary** [comment]
Please close the issue if no further action is needed @nehahimane

**Comment by nehahimane** [comment]
> The fields in Job and Resume objects in the admin portal are: Job: Position, Description, ApplicationDeadline, Status, Employer Resume: Summary, Education, Experience, Skills, File
> 
> Can you please elaborate?

Sure. It was creating the resumes for candidates for example for candidate abc there's resume 21, for candidate xyz there's resume 23. but i think this is generated by the framework so closing the issue. Thanks!
