### ISSUE TITLE
As an employer, while creating profile there's no restriction on total number of digits in phone number

### ISSUE THREAD

**Issue by nehahimane** [harshchauhdary/Solvers-Soen6011summer2023#31]

**Comment by harshchauhdary** [comment]
I have already put a restriction of 10-15 digits on the phone number when creating a profile either as an employer or candidate.

**Comment by harshchauhdary** [comment]
Please close the issue if no further action is needed @nehahimane

**Comment by nehahimane** [comment]
I have not considered the maximum length while testing. If that's the case it looks good to me. Closing the issue.
