### ISSUE TITLE
Sprint Documentation - Sprint 1

### ISSUE THREAD

**Issue by harshchauhdary** [harshchauhdary/Solvers-Soen6011summer2023#6]
- Create a document containing the backlog of user stories for Sprint 1.
- Add task breakdown.
- Include any open issues or plans for the next sprint in the document.

**Comment by shabuj-buet** [comment]
[Solvers-Soen6011summer2023.pdf](https://github.com/harshchauhdary/Solvers-Soen6011summer2023/files/12034621/Solvers-Soen6011summer2023.pdf)
Sprint 1 Document

**Comment by shabuj-buet** [comment]
Final Sprint 1 Project Document Published.
