### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by JoumanaDargham** [harshchauhdary/Solvers-Soen6011summer2023#8]
Hello,
I assume that you are going to add user stories, tasks for each user story as well as you'll update the readme file and the minutes of the meetings...
Good luck

**Comment by harshchauhdary** [comment]
We have added meeting minutes to the Wiki, we will link it to an issue. We have also written user stories, etc in a document but are yet to commit it.

**Comment by JoumanaDargham** [comment]
Good... Just I added comments... but you are the owners of the work!!
